/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTC7 (number 79), ws
  @{ */
#define BOARD_INITPINS_ws_PERIPHERAL I2S0                    /*!<@brief Device name: I2S0 */
#define BOARD_INITPINS_ws_SIGNAL RX_FS                       /*!<@brief I2S0 signal: RX_FS */
#define BOARD_INITPINS_ws_PORT PORTC                         /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_ws_PIN 7U                             /*!<@brief PORTC pin index: 7 */
#define BOARD_INITPINS_ws_PIN_NAME I2S0_RX_FS                /*!<@brief Pin name */
#define BOARD_INITPINS_ws_LABEL "ws"                         /*!<@brief Label */
#define BOARD_INITPINS_ws_NAME "ws"                          /*!<@brief Identifier name */
#define BOARD_INITPINS_ws_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                             /* @} */

/*! @name PORTC5 (number 77), data
  @{ */
#define BOARD_INITPINS_data_PERIPHERAL I2S0    /*!<@brief Device name: I2S0 */
#define BOARD_INITPINS_data_SIGNAL RXD0        /*!<@brief I2S0 signal: RXD0 */
#define BOARD_INITPINS_data_PORT PORTC         /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_data_PIN 5U             /*!<@brief PORTC pin index: 5 */
#define BOARD_INITPINS_data_PIN_NAME I2S0_RXD0 /*!<@brief Pin name */
#define BOARD_INITPINS_data_LABEL "data"       /*!<@brief Label */
#define BOARD_INITPINS_data_NAME "data"        /*!<@brief Identifier name */
                                               /* @} */

/*! @name PORTC9 (number 81), bclk
  @{ */
#define BOARD_INITPINS_bclk_PERIPHERAL I2S0                    /*!<@brief Device name: I2S0 */
#define BOARD_INITPINS_bclk_SIGNAL RX_BCLK                     /*!<@brief I2S0 signal: RX_BCLK */
#define BOARD_INITPINS_bclk_PORT PORTC                         /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_bclk_PIN 9U                             /*!<@brief PORTC pin index: 9 */
#define BOARD_INITPINS_bclk_PIN_NAME I2S0_RX_BCLK              /*!<@brief Pin name */
#define BOARD_INITPINS_bclk_LABEL "bclk"                       /*!<@brief Label */
#define BOARD_INITPINS_bclk_NAME "bclk"                        /*!<@brief Identifier name */
#define BOARD_INITPINS_bclk_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
